package com.birblett.helper;

public enum Ability {

    DASHMASTER,
    DULLAHAN,
    LUDFRU,
    KILLER_PILLAR,
    SLAMMER,
    ZOMBIE_KING,
    BOT,
    GUNNER,
    ZOMBIE_MAGE,

    IGNORE_EXPLOSION,
    IGNORE_FALL,
    IGNORE_FIRE,
    IGNORE_IFRAMES,
    IGNORE_LIGHTNING,
    IGNORE_SUFFOCATION,
    IGNORE_WATER,
    IGNORE_FAR_DAMAGE,

    BOSS_FLAG,
    CAN_DESPAWN_WITH_PARENT,
    CLIP_OWNER,
    DUMMY,
    ELITE,
    GRAPPLING,
    IMPORTANT,
    LINE_OF_SIGHT_DAMAGE,
    NOCLIP,
    OWNED,
    PHYSICS,
    SUMMON_ARROWS,
    SUMMON_LIGHTNING,
    ZOMBIE_IGNORE_WATER;

}
